<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * The Content-Security-Policy every application response carries (Phase 12, the security pass).
 *
 * ## Why this is here and not in `deploy/nginx.conf`
 *
 * `deploy/nginx.conf` owns the three headers it already sets and HSTS, because those are facts
 * about the *transport* and have to be true of responses PHP never sees — a static asset under
 * `/build/`, an nginx error page. A CSP is a fact about *this document*, and it is coupled to
 * exactly one thing that is generated by the application: the hash of the inline theme script in
 * `resources/views/app.blade.php`. Put the policy in nginx and that coupling is invisible in both
 * files and unverifiable on a machine with no nginx on it; put it here and
 * `tests/Feature/Middleware/ContentSecurityPolicyTest.php` recomputes the hash **from the
 * rendered page** and fails the moment somebody edits that script — which is the only way a
 * hash-based policy is safe to own.
 *
 * ## The policy, directive by directive, and what forced each one
 *
 * Measured against the real built assets (`npm run build`, then every shell loaded in Chromium
 * with this policy enforcing and the console read — not reasoned about).
 *
 *   - **`default-src 'self'`** — the floor. Everything below either narrows it or names the one
 *     origin that is not us.
 *   - **`script-src 'self' 'sha256-…'`** — the hash is the theme script in `app.blade.php`, which
 *     runs synchronously in `<head>` so the document is already `dark` before first paint. It
 *     cannot be moved into the bundle without reintroducing the flash it exists to prevent, so
 *     it is inline, and a hash is what makes an inline script allowed without
 *     `'unsafe-inline'` — which a hash also *disables* for scripts, so the two cannot be
 *     confused for one another. **No `'unsafe-eval'`:** Vue templates are compiled at build time
 *     and `grep -c 'new Function('` over `public/build/assets/app-*.js` is 0.
 *     Inertia's own `<script data-page="app" type="application/json">` is a **data block**, not
 *     an executable script, and Chromium does not check it against `script-src` — asserted in
 *     the browser rather than assumed, because a wrong guess here is a blank page.
 *   - **`style-src 'self' 'unsafe-inline' https://fonts.bunny.net`** — `'unsafe-inline'` is
 *     forced, and it is worth being exact about by what, because it is the one weakness in this
 *     policy:
 *       1. **Vue `:style` bindings.** Every Gantt bar's geometry, every chart's CSS variables
 *          (`Charts/chartTokens.ts`) and every reka-ui popover's position are inline `style`
 *          attributes. `style-src` governs those, and there is no per-attribute hash short of
 *          `style-src-attr 'unsafe-hashes'` with a hash per distinct value — impossible for
 *          computed geometry.
 *       2. **`@unovis/ts` injects `<style>` elements at runtime.** Its bundled CSS-in-JS sheet
 *          calls `document.createElement("style")` and `insertRule` — visible in
 *          `public/build/assets/BarCompare-*.js`. Every chart on every dashboard and report
 *          depends on it.
 *     A nonce would not help: it would have to be on markup Vue and Unovis create themselves.
 *     The honest intermediate is what is written here — inline *styles* are allowed, inline
 *     *scripts* are not, and `object-src`, `base-uri`, `frame-ancestors` and `form-action` close
 *     the injection routes that do not need script at all. Removing `'unsafe-inline'` from
 *     `style-src` means dropping `@unovis` and hand-writing the charts' SVG; that is a phase of
 *     its own, not a line in a hardening slice.
 *   - **`font-src 'self' https://fonts.bunny.net`** and the same origin on `style-src`, because
 *     `app.blade.php` loads Inter from Bunny's font CDN, which answers with a stylesheet whose
 *     `@font-face` rules point back at itself.
 *   - **`img-src 'self' data: blob:`** — `data:` for the inline SVG favicon and any data URI a
 *     chart or an icon resolves to; `blob:` because the voice recorder previews a recording it
 *     has not uploaded yet from an object URL.
 *   - **`media-src 'self' blob:`** — the same recorder, and the `<audio src>` an attached voice
 *     note plays from.
 *   - **`connect-src 'self' blob:` plus the Reverb origin** — Inertia's XHR, the command palette's
 *     `fetch('/search')`, the bell's poll, and the websocket. `blob:` because the voice player
 *     reads the recorder's unsent clip (an object URL) to draw its waveform (12-77).
 *
 *     A websocket matches `'self'` when it is the secure upgrade of the document's own origin
 *     (CSP3 §6.6.2.6), which on the VPS is true: `deploy/install.sh` sets `REVERB_HOST` to the
 *     site's own domain on 443. **It is not true anywhere else, and shipping it as if it were
 *     cost the client their socket.** `start-hq.bat` serves the app on `:8000` and Reverb on
 *     `:8080`, and a different port is a different origin — so every `new WebSocket()` was
 *     refused by this policy, on the one machine the client actually uses, and the screens fell
 *     back to polling while showing *"Reconnecting"*. Nothing failed loudly; the realtime build
 *     simply behaved like the polling build.
 *
 *     So the policy names the origin **the application's own configuration says it will dial**:
 *     {@see reverbOrigin()} reads the same `broadcasting.connections.reverb.options` the client
 *     is handed, and adds `ws://host:port` and `wss://host:port`. When that origin is already
 *     the document's — the VPS case — it adds nothing and the directive is what it always was.
 *     This is narrower than a blanket loosening: it is one host and one port, and it is the one
 *     the app would connect to anyway.
 *   - **`object-src 'none'`, `base-uri 'self'`, `form-action 'self'`, `frame-src 'none'`,
 *     `worker-src 'self' blob:`** — nothing here embeds a plugin, rewrites the document base,
 *     posts a form off-site or frames anything. `frame-ancestors 'self'` is the modern spelling
 *     of the `X-Frame-Options: SAMEORIGIN` nginx already sends; both are kept, because the
 *     nginx one also covers responses that never reach PHP.
 *
 * ## What it deliberately does not do
 *
 * No `upgrade-insecure-requests`: it would rewrite `http://127.0.0.1:8019` requests in local
 * development into `https://` and break every asset. HTTPS is a deploy-time guarantee and
 * belongs in nginx, where it is HSTS plus certbot's redirect.
 *
 * No `report-uri`/`report-to`: there is no endpoint to collect to, and the master prompt's
 * Part H forbids adding a third-party service for one.
 *
 * The download route sets **its own, much tighter** CSP on the bytes it streams
 * (`FileService::download()` — `default-src 'none'; … sandbox`). That is not this policy relaxed,
 * it is a different document with a different threat, and this middleware never overwrites a
 * response that already carries the header.
 */
class ContentSecurityPolicy
{
    /**
     * The sha256 of the inline theme script in `resources/views/app.blade.php`.
     *
     * Base64 of the digest of the bytes **between** `<script>` and `</script>`, indentation and
     * newlines included. Recomputed from the rendered page by
     * `tests/Feature/Middleware/ContentSecurityPolicyTest.php`, which is the only thing standing
     * between an edit to that script and a theme that stops applying before first paint with
     * nothing but a console message to say so.
     */
    public const THEME_SCRIPT_HASH = 'sha256-23n0ZlX2HsArnvsj8hhmNTee7fndsT6DlE+ybPDRpps=';

    /** Where the Inter webfont and its stylesheet come from. */
    private const FONT_ORIGIN = 'https://fonts.bunny.net';

    public function handle(Request $request, Closure $next): Response
    {
        $response = $next($request);

        // FileService::download() ships its own, stricter policy with the bytes. A response that
        // has already decided its policy keeps it.
        if (! $response->headers->has('Content-Security-Policy')) {
            $response->headers->set('Content-Security-Policy', self::policy());
        }

        return $response;
    }

    /** The policy as one header value. Public so the test asserts the real string. */
    public static function policy(): string
    {
        return implode('; ', [
            "default-src 'self'",
            "base-uri 'self'",
            "object-src 'none'",
            "frame-src 'none'",
            "frame-ancestors 'self'",
            "form-action 'self'",
            "script-src 'self' '".self::THEME_SCRIPT_HASH."'",
            "style-src 'self' 'unsafe-inline' ".self::FONT_ORIGIN,
            'font-src \'self\' '.self::FONT_ORIGIN,
            "img-src 'self' data: blob:",
            "media-src 'self' blob:",
            rtrim("connect-src 'self' blob: ".self::reverbOrigin()),
            "worker-src 'self' blob:",
            "manifest-src 'self'",
        ]);
    }

    /**
     * The websocket origin this application is configured to dial, as CSP source expressions.
     *
     * Empty when broadcasting is not Reverb, when no host is configured, or when the host and
     * port are already the document's own origin — in all three cases `'self'` covers it and a
     * redundant source would only be noise in a header somebody has to read.
     *
     * Both schemes are listed because the client picks one from `VITE_REVERB_SCHEME` at build
     * time and the server cannot know which bundle is being served; naming the pair is one
     * origin either way, and guessing wrong is the silent failure this method exists to end.
     */
    private static function reverbOrigin(): string
    {
        if (config('broadcasting.default') !== 'reverb') {
            return '';
        }

        $host = (string) config('broadcasting.connections.reverb.options.host', '');

        if ($host === '') {
            return '';
        }

        $port = (int) config('broadcasting.connections.reverb.options.port', 443);
        $authority = $host.':'.$port;

        // Already the document's origin: `'self'` covers the upgrade (CSP3 §6.6.2.6).
        $request = request();

        if ($request !== null && $request->getHost() === $host && $request->getPort() === $port) {
            return '';
        }

        return 'ws://'.$authority.' wss://'.$authority;
    }
}
