<?php

namespace App\Http\Requests\Time;

use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Support\Carbon;

/**
 * Starting the timer on a task.
 *
 * `client_uuid` is **required**, and generated by the browser before the request leaves it. That
 * is what makes the start idempotent: a widget that sent it, lost the connection before the
 * reply and sent it again gets back the entry it already made. A server-generated id could not
 * do that job, because the client would have nothing to ask about.
 *
 * `started_at` is optional and is the client's own clock — sent when the widget started while
 * offline and is only now reaching the server. `TimerService` clamps anything in the future; the
 * rule here is only that it is a date.
 */
class StartTimerRequest extends TimerRequest
{
    /**
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            // `exists` only says the row is there. WHOSE task it is, is decided by resolving it
            // through Task::visibleTo() in the controller, so timing against somebody else's
            // task answers 404 rather than a validation message that confirms it exists.
            'task_id' => ['required', 'integer', 'exists:tasks,id'],
            'client_uuid' => ['required', 'uuid'],
            'started_at' => ['nullable', 'date'],
        ];
    }

    public function taskId(): int
    {
        return (int) $this->validated('task_id');
    }

    public function clientUuid(): string
    {
        return (string) $this->validated('client_uuid');
    }

    public function startedAt(): ?Carbon
    {
        return $this->moment('started_at');
    }
}
