<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Paired timer extensions (Phase 11, decision 11-01; contract `docs/extension-api.md`).
     *
     * One row is one browser install paired to one user. `install_uuid` is generated by the
     * extension on install, so pairing the same install twice lands on the same row instead of a
     * second one. `token_id` points at the Sanctum token the install was issued; it is set null
     * when the token is deleted, and `revoked_at` records that the device was unpaired.
     */
    public function up(): void
    {
        Schema::create('devices', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
            $table->string('kind', 20)->default('extension');
            $table->string('name', 120);
            $table->unsignedBigInteger('token_id')->nullable();
            $table->foreign('token_id')->references('id')->on('personal_access_tokens')->nullOnDelete();
            $table->uuid('install_uuid');
            $table->timestampTz('paired_at');
            $table->timestampTz('last_seen_at')->nullable();
            $table->timestampTz('revoked_at')->nullable();
            $table->timestamps();

            $table->unique(['user_id', 'install_uuid']);
            $table->index('token_id');
        });

        DB::statement(<<<'SQL'
            alter table devices
            add constraint devices_kind_check
            check (kind in ('extension'))
        SQL);
    }

    public function down(): void
    {
        Schema::dropIfExists('devices');
    }
};
